-- Run this entire file once in Supabase SQL Editor.
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique not null,
  display_name text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.settings (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  key text not null,
  value text not null,
  unique(user_id,key)
);

create table if not exists public.workouts (
 id bigint generated by default as identity primary key, user_id uuid not null references auth.users(id) on delete cascade,
 date date not null, muscle_group text not null, exercise text not null, sets integer not null, reps integer not null, weight_kg numeric not null, rpe numeric not null, created_at timestamptz not null default now()
);
create table if not exists public.cardio (
 id bigint generated by default as identity primary key, user_id uuid not null references auth.users(id) on delete cascade,
 date date not null, activity text not null, duration_min numeric not null, distance_km numeric not null, avg_hr integer, notes text, pace_min_km numeric, created_at timestamptz not null default now()
);
create table if not exists public.tests (
 id bigint generated by default as identity primary key, user_id uuid not null references auth.users(id) on delete cascade,
 date date not null, pullups numeric, pushups_2min numeric, situps_2min numeric, run_1500_sec numeric, swim_min numeric, water_tread_min numeric, readiness_score numeric, created_at timestamptz not null default now()
);
create table if not exists public.meals (
 id bigint generated by default as identity primary key, user_id uuid not null references auth.users(id) on delete cascade,
 date date not null, meal_type text not null, calories numeric not null, protein_g numeric not null, carbs_g numeric not null, fats_g numeric not null, description text, created_at timestamptz not null default now()
);
create table if not exists public.body (
 id bigint generated by default as identity primary key, user_id uuid not null references auth.users(id) on delete cascade,
 date date not null, weight_kg numeric not null, body_fat numeric, chest_cm numeric, arm_cm numeric, waist_cm numeric, created_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles(id,username,display_name) values (
    new.id,
    coalesce(new.raw_user_meta_data->>'username', split_part(new.email,'@',1)),
    coalesce(new.raw_user_meta_data->>'display_name', split_part(new.email,'@',1))
  ) on conflict (id) do nothing;
  insert into public.settings(user_id,key,value) values
    (new.id,'calorie_target','3000'),(new.id,'protein_target','150'),(new.id,'weight_target','80')
  on conflict (user_id,key) do nothing;
  return new;
end; $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.settings enable row level security;
alter table public.workouts enable row level security;
alter table public.cardio enable row level security;
alter table public.tests enable row level security;
alter table public.meals enable row level security;
alter table public.body enable row level security;

create policy "profiles own" on public.profiles for all using (auth.uid()=id) with check (auth.uid()=id);
create policy "settings own" on public.settings for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy "workouts own" on public.workouts for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy "cardio own" on public.cardio for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy "tests own" on public.tests for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy "meals own" on public.meals for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy "body own" on public.body for all using (auth.uid()=user_id) with check (auth.uid()=user_id);

-- Helpful indexes
create index if not exists workouts_user_date on public.workouts(user_id,date);
create index if not exists cardio_user_date on public.cardio(user_id,date);
create index if not exists tests_user_date on public.tests(user_id,date);
create index if not exists meals_user_date on public.meals(user_id,date);
create index if not exists body_user_date on public.body(user_id,date);
